# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            DATA 101
tagline:          'A Jekyll theme'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/abdimoh/data-101
